### ISSUE TITLE
SASM hangs by pressing ctrl+r (show registers) under ubuntu 16.04

### ISSUE THREAD

**Issue by Moneysac90** [Dman95/SASM#58]
By pressing ctrl + r (show registers) SASM doesn't respond anymore. A complete reboot is required to run SASM again.

**Comment by Dman95** [comment]
I need more extended information about it. On my Ubuntu with SASM 3.5 the bug is not reproduced. Specify please version of your SASM, the source code of the program on which the bug is reproduced. Also please give a screenshot of the "Build" tab in the settings.

**Comment by amar-laksh** [comment]
The bug is certainly present. The SASM version is `3.5.1-0` and my System configuration is -
![all](https://cloud.githubusercontent.com/assets/12481356/18323311/988162ae-7554-11e6-9e39-a9501beab83f.jpg)

After ctrl + r is pressed the there seems no response from SASM. Even if the process is killed it cannot be started again. The only solution becomes to logout the account. 

A simple strace yields this (which is quite fascinating, connect call? ):
![screenshot from 2016-09-07 23-52-17](https://cloud.githubusercontent.com/assets/12481356/18323574/d5c01c68-7555-11e6-8a6f-2a6b86cb8eb6.png)

Maybe this could be helpful

**Comment by Dman95** [comment]
@amar-laksh What the code do you try to start?

**Comment by amar-laksh** [comment]
Okay so I ran SASM again from a root shell, ctrl+r works perfectly fine. 

Now when a user shell is used to run SASM the bug is repeated and this is the strace
![screenshot from 2016-09-08 00-11-36](https://cloud.githubusercontent.com/assets/12481356/18324197/e0aecc2a-7558-11e6-81d3-b14c5a022dc7.png)

Clearly it can't find the Project conf there. I think you just need to add an exception for fileNotFound there @Dman95 :dancer:

**Comment by Moneysac90** [comment]
Try it with the following program. SASM settings are 
![screenshot_20160908_124101](https://cloud.githubusercontent.com/assets/20662108/18346676/e0d81102-75c1-11e6-9f9d-47bbeb747299.png)


 section .data
 hello db 'H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd', '!', 0xa
 len equ $ - hello
 
 section .text
 global _start
 _start:
 mov eax, 4 ; write ( stdout , hello , len )
 mov ebx, 1
 mov ecx, hello
 mov edx, len
 int 80h
 
 mov eax, 1 ; exit (0)
 mov ebx, 0
 int 80h

**Comment by amar-laksh** [comment]
@Dman95 , The following program works but cleanly exits. It exits even in Debug mode with Breakpoint set. So can't test the ctrl+r.   
![debug](https://cloud.githubusercontent.com/assets/12481356/18357195/9c7b61de-760d-11e6-8a5b-fd93abc3a36d.jpg)

**Comment by Dman95** [comment]
I still can't reproducing the bug. Can anyone give me an example for reproducing it, please?

**Comment by fat-crocodile** [comment]
SASM 3.7.0, Fedora 23
Even auto generated new program immediately hang trying to show all registers (if choose option "show all registers").

**Comment by fat-crocodile** [comment]
Just tested my gdb (version Fedora 7.10.1-31.fc23), in console command "info all-registers" worked correctly.

**Comment by fat-crocodile** [comment]
It seems, that gdb registers format output depends on gdb version (or may be some gdb settings? I don't know). 
Look into your debugger.cpp file, line 429, registers loop. 
My gdb print mxcsr before ymmX on line 33 (mxscr -- i == 32 and ymmX i >= 33 && i <= 40). Your code obviously expects vise versa.

Sorry, but your code in this place is really not reliable. Much better would be read register name and deduce format from it.

**Comment by fat-crocodile** [comment]
Would it be OK if I try to fix it, or you prefer doing it yourself?

**Comment by fat-crocodile** [comment]
And my gdb version shows ymmX registers like this:

```
ymm0           {v8_float = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, v4_double = {0x0, 0x0, 0x0, 0x0}, v32_int8 = {0x0 <repeats 32 times>}, v16_int16 = {0x0 <repeats 16 times>}, v8_int32 = {0x0, 0x0, 0x0, 0x0, 
    0x0, 0x0, 0x0, 0x0}, v4_int64 = {0x0, 0x0, 0x0, 0x0}, v2_int128 = {0x00000000000000000000000000000000, 0x00000000000000000000000000000000}}
```

there are no "uint128" at all. And gdb does not show xmmX registers in all registers list, only if I write command "print $xmm0" or "info register xmm0" (and there are "uint128"). Probably gdb consider xmm as part of ymm (like ax and eax).

**Comment by Dman95** [comment]
Now (in SASM 3.8.0) it should be fixed. Thanks everyone!
