### ISSUE TITLE
Not everything compiles to exe

### ISSUE THREAD

**Issue by aanunez** [Dman95/SASM#74]
In mainwindow.cpp we have ... 
`    if (QFile::exists(Common::pathInTemp("SASMprog.exe")))`
but I do not expect to assemble to exe, I am creating a bootloader (img or bin is the final result). 

The result, when assembling to bin is the following...
```
[16:25:12] Build started...
[16:25:12] Warning! Errors have occurred in the build:
```
No actual errors are listed as none have occurred.

I think the Ideal solution would be to allow a "run" option after assembly is complete. If enabled then then the ".exe" check is skipped and arbitrary code specified in settings is executed. I would be using this to get right into qemu.

Update:
I think this is a generic seems to be a generic "Disable Linker" problem. We shouldn't look for the exe if the linker is disabled. This issue occurs on the example "hello world" project.

**Comment by Dman95** [comment]
In current situation you can compile only executable binaries for your machine using SASM. Any other formats are not supported. And even if you compile non-executable , you won't be able to run/debug it. In this situation usage of SASM doesn't differ from usage of simple text editor and console.

I can't disable looking for exe, because in this way I won't be able to check if program was compiled. Disable linker option is only for situations, where you can build resulting executable by one step using assembler.

Maybe in future SASM architecture of build/run/debug system can be changed to more flexible. But current situation is as described above.
